image: python:3.12

stages:
  - formatting
  - linting
  - testing

cache:
  paths:
    - .cache/pip

before_script:
  - python -V
  - pip install --upgrade pip
  - pip install -r requirements/develop.txt

formatting:
  stage: formatting
  script:
    - black --check .

linting:
  stage: linting
  script:
    - mypy --ignore-missing-imports --exclude venv .

testing:
  stage: testing
  variables:
    ENVIRONMENT: GITLAB
  before_script:
    - python -V
    - pip install --upgrade pip
    - pip install -r requirements/develop.txt
  script:
    - pytest
