image: python:3.12

stages:
  - formatting
  - linting
  - testing

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install -U pip
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements/develop.txt

formatting:
  stage: formatting
  script:
    - pip install black==25.1.0
    - black --check .

linting:
  stage: linting
  script:
    - pip install mypy==1.15.0
    - mypy --ignore-missing-imports --exclude venv .

testing:
  stage: testing
  script:
    - pip install pytest
    - pytest -m "not database_integration"
