[pytest]
log_cli = true
log_format = %(asctime)s  %(name)s  %(levelname)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
log_cli_level = INFO
markers =
    skip_in_main_suite: mark a test as excluded from the main test suite

filterwarnings =
    ignore::FutureWarning

asyncio_mode = auto
