[pytest]
log_cli = true
log_format = %(asctime)s  %(name)s  %(levelname)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
log_cli_level = INFO
markers =
    database_integration: mark a test as excluded from the main test suite

filterwarnings =
    ignore::FutureWarning
    ignore:.*WebSocketClientProtocol.*:DeprecationWarning
    ignore:.*websockets\.legacy.*:DeprecationWarning

asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
